version: '3.7'
services:
    web:
        image: nginx:1.15.6
        ports:
        - '8000:80'
        depends_on:
        - app
        volumes:
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    client:
        container_name: client
        build: ./docker/client
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/nuxt
        environment:
            PORT: 3000
            HOST: 0.0.0.0
        command: './compose-cmd.bash'
    app:
        build: ./docker/php
        volumes:
        - .:/var/www/html
        depends_on:
        - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sample1
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - mysql-data:/var/lib/mysql
volumes:
    mysql-data: